version: '3'
services:

    cubes_solver_env:
        container_name: python_env
        build:
            dockerfile: Dockerfile
        deploy:
            resources:
                limits:
                    memory: 8192M
